name: Deploy

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /root/docker-laravel-development/code/laravel11 &&
          git pull origin production &&
          php artisan -v &&
          exit"


#run: git pull origin production
#script: "cd /root/docker-laravel-development/code/laravel11 && ./.scripts/deploy.sh"
#  echo "Deployment started ..."
#  echo "Dang deploy.... "
  ## Enter maintenance mode or return true
  ## if already is in maintenance mode
  #(php artisan down) || true
  #
  ## Pull the latest version of the app
#  git pull origin production
#
## Install composer dependencies
#composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
#
## Clear the old cache
#php artisan clear-compiled
#
## Recreate cache
#php artisan optimize
#
## Compile npm assets
#npm run prod
#
## Run database migrations
#php artisan migrate --force
#
## Exit maintenance mode
#php artisan up
